ThuVienDienTu/Areas/Admin/Controllers/CensorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ThuVienDienTu.Data;
using ThuVienDienTu.Models;
using ThuVienDienTu.Models.ViewModels;
using ThuVienDienTu.Utility;

namespace ThuVienDienTu.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ADMIN_ROLE + "," + SD.CENSOR_ROLE)]
    [Area("Admin")]
    public class CensorController : Controller
    {
        private readonly ApplicationDbContext _db;
        private int PageSize = 10;
        [BindProperty]
        public BooksViewModel BooksVM { get; set; }
        public CensorController(ApplicationDbContext db)
        {
            _db = db;
            BooksVM = new BooksViewModel()
            {
                Books = new List<Book>(),
                Book = new Book(),
                PagingInfo = new PagingInfo()
            };
        }
        public async Task<IActionResult> Index(int productPage = 1)
        {
            StringBuilder param = new StringBuilder();
            param.Append("/Admin/Censor?productPage=:");
            var bookOnQueue = await _db.Books.ToListAsync();
            var count = bookOnQueue.Count;
            bookOnQueue.Skip((productPage - 1) * PageSize).Take(PageSize).ToList();
            BooksVM.Books = bookOnQueue;
            BooksVM.PagingInfo = new PagingInfo()
            {
                CurrentPage = productPage,
                ItemsPerPage = PageSize,
                TotalItems = count,
                urlParam = param.ToString()
            };
            return View(BooksVM);
        }
        public async Task<IActionResult> Details(int id)
        {
            var book = await _db.Books.Where(u => u.Id == id).Include(a => a.Author).Include(b => b.Publisher).FirstOrDefaultAsync();
            var chapterOfBook = await _db.Chapters.Where(u => u.BookId == id).ToListAsync();
            book.Chapters = chapterOfBook;
            return View(book);

        }
        public async Task<IActionResult> ChapterApprove(int id)
        {
            var chapter = await  _db.Chapters.Where(u => u.Id == id).FirstOrDefaultAsync();
            chapter.Approved = true;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Read", new {area = "Customer", id = chapter.BookId});
        }
        public async Task<IActionResult> ChapterDecline(int id)
        {
            var chapter = await _db.Chapters.Where(u => u.Id == id).FirstOrDefaultAsync();
            chapter.Approved = true;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Read", new { area = "Customer", id = chapter.BookId });
        }
        public async Task<IActionResult> Publish(int id)
        {
            var book = await _db.Books.Where(u => u.Id == id).FirstOrDefaultAsync();
            if(book.Approved)
            {
                book.Approved = false;
            }
            else
            {
                book.Approved = true;
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", new { productPage = 1 });
        }
    }
}

ThuVienDienTu/Areas/Admin/Views/Censor/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model ThuVienDienTu.Models.Book
@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThuVienDienTu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">


    <link rel="stylesheet" href="~/css/style.css">
    <style>
        ::-webkit-scrollbar {
            width: 10px;
        }

        /* Track */
        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        /* Handle */
        ::-webkit-scrollbar-thumb {
            background: #888;
        }

            /* Handle on hover */
            ::-webkit-scrollbar-thumb:hover {
                background: #555;
            }
    </style>

    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //tags -->
    @*<link href="\product_detail\css\bootstrap.css" rel="stylesheet" type="text/css" media="all" />*@
    <link rel="stylesheet" href="\product_detail\css\flexslider.css" type="text/css" media="screen" />
    <link href="\product_detail\css\font-awesome.css" rel="stylesheet">
    <link href="\product_detail\css\easy-responsive-tabs.css" rel='stylesheet' type='text/css' />
    <link href="\product_detail\css\style.css" rel="stylesheet" type="text/css" media="all" />

    <!-- //for bootstrap working -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <h1 style="text-align:center;color:grey;margin-top:40px;font-family:Bahnschrift;font-size:30px">CHI TIẾT</h1>
    <div class="site-section bg-light">
        <div class="container">
            @*<div class="row mb-5">
                    <div class="col-md-7">
                    </div>
                </div>*@
            <div class="col-md-6 single-right-left ">
                <ul class="slides">
                    <li data-thumb="images/d2.jpg">
                        <div class="thumb-image"> <img src="@Model.BookImage" data-imagezoom="true" class="img-responsive"> </div>
                    </li>

                </ul>
            </div>
            <div class="col-md-6 single-right-left simpleCart_shelfItem">
                <label>@Model.BookName</label>
                <br />
                Tác giả: <a asp-area="Admin" asp-controller="Authors" asp-action="Details" asp-route-id="@Model.Author.Id">@Model.Author.Signed</a> <br />
                NXB: <a asp-area="Admin" asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.Publisher.Id">@Model.Publisher.PublisherName</a>
                <p>Giá: @Model.BookPrice Lượng</p>
                <br />
            </div>
            <div class="responsive_tabs_agileits">
                <div id="horizontalTab">

                    <div class="resp-tabs-container">
                        <!--/tab_one-->
                        <div class="tab1">

                            <div class="single_page_agile_its_w3ls">
                                <ul class="link">
                                    <li id="tab-1" class="link-item active" onclick="ShowDescr()">Giới thiệu</li>
                                    <li id="tab-2" class="link-item" onclick="ShowListChapter()">Danh sách chương</li>
                                </ul>
                                <textarea id="description" class="content" readonly disabled style="width:600px;height:400px;resize:none;box-shadow:none;border:none">
                                        @Model.Description
                                </textarea>
                                <section id="listChapter" class="content" style="width:600px;height:400px;" hidden>
                                    @if (Model.Chapters.Count > 0)
                                    {
                                        foreach (var chapter in Model.Chapters)
                                        {
                                            if (chapter.Price > 0)
                                            {
                                                <i class="far fa-money-bill-alt"></i>
                                            }<span><a asp-area="Customer" asp-controller="Read" asp-action="ReadingChapter" asp-route-id="@chapter.Id"> @chapter.Chaptername</a></span>
                                            <br />
                                        }
                                    }
                                    else
                                    {
                                        <p style="text-align:center">Chưa có chương</p>
                                    }
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function Submit() {
            document.getElementById("DetailForm").Submit();
        }
        function ShowDescr() {
            document.getElementById("description").hidden = false;
            document.getElementById("listChapter").hidden = true;
            var element = document.getElementById("tab-1");
            if (!element.classList.contains("active")) {
                element.classList.add("active")
            };
            var element = document.getElementById("tab-2");
            element.classList.remove("active");
        }
        function ShowListChapter() {
            document.getElementById("description").hidden = true;
            document.getElementById("listChapter").hidden = false;
            var element = document.getElementById("tab-2");
            element.classList.add("active");
            var element = document.getElementById("tab-1");
            element.classList.remove("active");
        }
        function ShowComment() {
            document.getElementById("description").hidden = true;
            document.getElementById("listChapter").hidden = true;
            var element = document.getElementById("tab-1");
            element.classList.remove("active");
            var element = document.getElementById("tab-2");
            element.classList.remove("active");
        }
        function ShowReview() {
            document.getElementById("description").hidden = true;
            document.getElementById("listChapter").hidden = true;
            var element = document.getElementById("tab-1");
            element.classList.remove("active");
            var element = document.getElementById("tab-2");
            element.classList.remove("active");
        }
    </script>

    <!--//slider_owl-->
    <!-- js -->
    <script type="text/javascript" src="\product_detail\js\jquery-2.1.4.min.js"></script>
    <!-- //js -->
    <script src="\product_detail\js\modernizr.custom.js"></script>
    <!-- Custom-JavaScript-File-Links -->
    <!-- cart-js -->
    <script src="\product_detail\js\minicart.min.js"></script>
    <script>
        // Mini Cart
        paypal.minicart.render({
            action: '#'
        });

        if (~window.location.search.indexOf('reset=true')) {
            paypal.minicart.reset();
        }
    </script>

    <!-- //cart-js -->
    <!-- single -->
    <script src="\product_detail\js\imagezoom.js"></script>
    <!-- single -->
    <!-- script for responsive tabs -->
    <script src="\product_detail\js\easy-responsive-tabs.js"></script>
    <script>
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true,   // 100% fit in a container
                closed: 'accordion', // Start closed if in accordion view
                activate: function (event) { // Callback function if tab is switched
                    var $tab = $(this);
                    var $info = $('#tabInfo');
                    var $name = $('span', $info);
                    $name.text($tab.text());
                    $info.show();
                }
            });
            $('#verticalTab').easyResponsiveTabs({
                type: 'vertical',
                width: 'auto',
                fit: true
            });
        });
    </script>
    <!-- FlexSlider -->
    <script src="\product_detail\js\jquery.flexslider.js"></script>
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });
    </script>
    <!-- //FlexSlider-->
    <!-- //script for responsive tabs -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="\product_detail\js\move-top.js"></script>
    <script type="text/javascript" src="\product_detail\js\jquery.easing.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
    <!-- for bootstrap working -->
    <script type="text/javascript" src="\product_detail\js\bootstrap.js"></script>
    <script>
        function CalculateSummary() {
            var price = document.getElementById("price").innerHTML;
            var amount = document.getElementById("itemamount").value;
            document.getElementById("summary").innerHTML = "Thành tiền: " + price * amount;
        }
    </script>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/stickyfill.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>

    <script src="~/js/jquery.fancybox.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/70d04a055c.js" crossorigin="anonymous"></script>
</body>
</html>

ThuVienDienTu/Areas/Admin/Views/Censor/Index.cshtml
@model ThuVienDienTu.Models.ViewModels.BooksViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<br />
<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-info"> Sách chờ duyệt</h2>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Book.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.BookImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.BookPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.Publisher)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Book.Accesscount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Books.Count > 0)
        {
            @foreach (var item in Model.Books)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookName)
                    </td>
                    <td>
                        <img src="@item.BookImage" alt="ảnh bìa sách" width="300" height="300" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Accesscount)
                    </td>
                    <td>
                        <div class="btn-group">
                            @if (item.Approved)
                            {
                                <a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="Censor" asp-action="Publish" asp-route-id="@item.Id"><i class="fas fa-arrow-circle-down"></i></a>

                            }
                            else
                            {
                                <a type="button" class="btn btn-primary" asp-area="Admin" asp-controller="Censor" asp-action="Publish" asp-route-id="@item.Id"><i class="fas fa-arrow-circle-up"></i></a>

                            }
                            <a type="button" class="btn btn-success" asp-area="Customer" asp-controller="Read" asp-action="Index" asp-route-id="@item.Id"><i class="fas fa-search"></i></a>
                            <a type="button" class="btn btn-info" asp-action="Details" asp-controller="Censor" asp-route-id="@item.Id"><i class="far fa-list-alt"></i></a>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<div page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
     page-class="btn border" page-class-normal="btn btn-default active"
     page-class-selected="btn btn-primary active" class="btn-group m-1"></div>