ThuVienDienTu/Models/Publisher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ThuVienDienTu.Models
{
    public class Publisher
    {
        public int Id { get; set; }
        [Display(Name = "Tên NXB")]
        public string PublisherName { get; set; }
        [Display(Name = "Logo NXB")]
        public string PublisherLogo { get; set; }
        [Display(Name ="Mô tả về NXB")]
        public string Description { get; set; }
        public virtual List<Book> Books { get; set; }
        [Display(Name = "Quốc gia")]
        public int CountryId { get; set; }
        public virtual Country Country { get; set; }
    }
}

ThuVienDienTu/Areas/Admin/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.CookiePolicy;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThuVienDienTu.Data;
using ThuVienDienTu.DesignPatterns.SingletonPatterns;
using ThuVienDienTu.Models;
using ThuVienDienTu.Utility;

namespace ThuVienDienTu.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class PublishersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ISingleton _iSingleton;
        private IWebHostEnvironment _hostEnvironment;
        public PublishersController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _iSingleton = Singleton.GetInstance;
        }

        // GET: Admin/Publishers
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        public async Task<IActionResult> Index()
        {
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName");
            var applicationDbContext = _context.Publishers.Include(p => p.Country);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Publishers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .Include(p => p.Country)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Admin/Publishers/Create
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        public IActionResult Create()
        {
            var countriesFromDb = _context.Countries.ToList();
            if (countriesFromDb == null)
            {
                return RedirectToAction("Create", "Countries");
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName");
            return View();
        }

        // POST: Admin/Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST(string publisherName, string description, int countryId)
        {
            try
            {
                Publisher publisher = new Publisher()
                {
                    PublisherName = publisherName,
                    Description = description,
                    CountryId = countryId
                };
                if (ModelState.IsValid)
                {
                    _context.Add(publisher);
                    await _context.SaveChangesAsync();
                    var webRootPath = _hostEnvironment.WebRootPath;
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count != 0)
                    {
                        var uploads = Path.Combine(webRootPath, SD.PublisherImageFolder);
                        var extension = Path.GetExtension(files[0].FileName);
                        using (var fileStream = new FileStream(Path.Combine(uploads, publisher.Id + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        };
                        publisher.PublisherLogo = @"\" + SD.PublisherImageFolder + @"\" + publisher.Id + extension;
                    }
                    else
                    {
                        var uploads = Path.Combine(webRootPath, SD.DefaultPublisherLogo);
                        System.IO.File.Copy(uploads, webRootPath + @"\" + SD.PublisherImageFolder + @"\" + publisher.Id + ".png");
                        publisher.PublisherLogo = @"\" + SD.PublisherImageFolder + @"\" + publisher.Id + ".png";
                    }
                    await _context.SaveChangesAsync();
                    _iSingleton.LogException("Thêm NXB Id: " + publisher.Id + " " + publisher.PublisherName);
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", publisher.CountryId);
                return View(publisher);
            }
            catch (Exception e)
            {
                _iSingleton.LogException(e.Message);
                return RedirectToAction("Error", "Log");
            }

        }

        // GET: Admin/Publishers/Edit/5
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", publisher.CountryId);
            return View(publisher);
        }

        // POST: Admin/Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PublisherName,PublisherLogo,Description,CountryId")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    var webRootPath = _hostEnvironment.WebRootPath;
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count > 0)
                    {
                        if (publisher.PublisherLogo != null)
                        {
                            var removeUpload = webRootPath + @"" + publisher.PublisherLogo;
                            System.IO.File.Delete(removeUpload);
                        }
                        var uploads = Path.Combine(webRootPath, SD.PublisherImageFolder);
                        var extension = Path.GetExtension(files[0].FileName);
                        using (var fileStream = new FileStream(Path.Combine(uploads, publisher.Id + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        publisher.PublisherLogo = @"\" + SD.PublisherImageFolder + @"\" + publisher.Id + extension;
                    }
                }
                catch (DbUpdateConcurrencyException e)
                {
                    if (!PublisherExists(publisher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        _iSingleton.LogException(e.Message);
                        return RedirectToAction("Error", "Log");
                    }
                }
                _iSingleton.LogException("Cập nhật NXB Id: " + id);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", publisher.CountryId);
            return View(publisher);

        }

        // GET: Admin/Publishers/Delete/5
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .Include(p => p.Country)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Admin/Publishers/Delete/5
        //[Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int publisherid)
        {
            var publisher = await _context.Publishers.FindAsync(publisherid);
            try
            {
                if (publisher.PublisherLogo != null)
                {
                    var webRootPath = _hostEnvironment.WebRootPath;
                    var removeUploaded = webRootPath + @"" + publisher.PublisherLogo;
                    System.IO.File.Delete(removeUploaded);
                }
                _context.Publishers.Remove(publisher);
                await _context.SaveChangesAsync();
                _iSingleton.LogException("Xóa NXB : " + publisher.PublisherName);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _iSingleton.LogException(e.Message);
                return RedirectToAction("Error", "Log");
            }
           
        }

        private bool PublisherExists(int id)
        {

ThuVienDienTu/Areas/Admin/Views/Publishers/Create.cshtml
@model ThuVienDienTu.Models.Publisher

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Create</h1>

<h4>Publisher</h4>
<hr />
<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="PublisherName" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="PublisherLogo" class="control-label"></label>
            </div>
            <div class="col-6">
                <input class="form-control" type="file" name="files" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Description" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="CountryId" class="control-label"></label>
            </div>
            <div class="col-6">
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Thêm NXB" class="btn btn-primary" />
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

ThuVienDienTu/Areas/Admin/Views/Publishers/Delete.cshtml
@model ThuVienDienTu.Models.Publisher

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherLogo)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.PublisherLogo" width="400" height="400"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại</a>
    </form>
</div>

ThuVienDienTu/Areas/Admin/Views/Publishers/Details.cshtml
@model ThuVienDienTu.Models.Publisher

@{
    ViewData["Title"] = "Details";
    @if (User.IsInRole(ThuVienDienTu.Utility.SD.ADMIN_ROLE) || User.IsInRole(ThuVienDienTu.Utility.SD.LIBRARIAN_ROLE))
    {
        Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
    }
}
<body>


    <h1 id="publisher" style="text-align:center;color:grey;margin-top:40px;font-family:Bahnschrift;font-size:30px">CHI TIẾT</h1>
    <div class="site-section bg-light">
        <div class="container">
            <h4>Nhà xuất bản</h4>
            <hr />
            <div class="row">
                <div class="col-lg-6">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PublisherName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PublisherName)
                        </dd>

                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CountryId)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Country.CountryName)
                        </dd>
                    </dl>
                    <div>
                        <a class="btn btn-outline-secondary rounded" asp-action="Index" asp-controller="Home" asp-area="Customer">Trang chủ</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="@Model.PublisherLogo" width="300" height="400" />
                </div>

            </div>
        </div>
    </div>
    @if (User.IsInRole(ThuVienDienTu.Utility.SD.ADMIN_ROLE) || User.IsInRole(ThuVienDienTu.Utility.SD.LIBRARIAN_ROLE))
    {
        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
    }
    <script>
        document.getElementById('publisher').scrollIntoView(true);
    </script>
</body>

ThuVienDienTu/Areas/Admin/Views/Publishers/Edit.cshtml
@model ThuVienDienTu.Models.Publisher

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Edit</h1>

<h4>Publisher</h4>
<hr />
<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <div class="col-3">
            <label asp-for="PublisherName" class="control-label"></label>
        </div>
        <div class="col-7">
            <input asp-for="PublisherName" class="form-control" />
            <span asp-validation-for="PublisherName" class="text-danger"></span>
        </div>   
    </div>
    <div class="form-group">
        <input hidden asp-for="PublisherLogo"/>      
        <div class="col-3">
            <label asp-for="PublisherLogo" class="control-label"></label>
            <img src="@Model.PublisherLogo" width="250" height="250"/>
        </div>
        <div class="col-7">
            <input class="form-control" type="file" name="files"/>
        </div>              
    </div>
    <div class="form-group">
        <div class="col-3">
            <label asp-for="Description" class="control-label"></label>
        </div>
        <div class="col-7">
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>            
    </div>
    <div class="form-group">
        <div class="col-3">
            <label asp-for="CountryId" class="control-label"></label>
        </div>
        <div class="col-7">
            <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
            <span asp-validation-for="CountryId" class="text-danger"></span>
        </div>    
    </div>
    <div class="form-group">
        <input type="submit" value="Lưu" class="btn btn-primary" />
    </div>
</form>


<div>
    <a asp-action="Index">Quay lại</a>
</div>

ThuVienDienTu/Areas/Admin/Views/Publishers/Index.cshtml
@model IEnumerable<ThuVienDienTu.Models.Publisher>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<br />
<br />
<body>
    <div class="row">
        <div class="col-6">
            <h2 class="text-info"> Danh sách NXB</h2>
        </div>
        <div class="col-6 text-right">
            <a href="#addPublisherModal" data-toggle="modal" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Thêm NXB</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PublisherName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublisherLogo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Country)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublisherName)
                    </td>
                    <td>
                        <img src="@item.PublisherLogo" width="300" height="300" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Country.Id)
                    </td>
                    <td>
                        <div class="btn-group">
                            <a type="button" class="btn btn-success" asp-action="Edit" asp-controller="Publishers" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                            <a type="button" class="btn btn-info" asp-action="Details" asp-controller="Publishers" asp-route-id="@item.Id"><i class="far fa-list-alt"></i></a>
                            <a id="@item.Id" href="#deletePublisherModal" class="btn btn-danger" onclick="DeleteUser(this.id)" data-toggle="modal"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="addPublisherModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form asp-action="Create" method="post" enctype="multipart/form-data">
                    <div class="modal-header">
                        <h4 class="modal-title">Thêm NXB</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">

                        <div class="p-4 border rounded">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                    <input name="publisherName" placeholder="Tên NXB" class="form-control" />
                            </div>
                            <div class="form-group row">
                                <div class="col-3">
                                    <label class="control-label">Logo NXB</label>
                                </div>
                                <div class="col-6">
                                    <input class="form-control" type="file" name="files" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-6">
                                    <input placeholder="Mô tả NXB" name="description" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-3">
                                    <label class="control-label">Quốc gia</label>
                                </div>
                                <div class="col-6">
                                    <select name="countryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-success" value="Thêm NXB">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Delete Modal HTML -->
    <div id="deletePublisherModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form asp-action="Delete" method="post">
                    <div class="modal-header">
                        <h4 class="modal-title">Xoá NXB</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Bạn có chắc muốn xoá NXB này </p>
                        <p class="text-warning"><small>Không thể hoàn tác.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Trở về">
                        <input type="hidden" name="publisherid" id="publisherid" />
                        <input type="submit" class="btn btn-danger" value="Xoá">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        function DeleteUser(id) {
            document.getElementById("publisherid").value = id;
        }
    </script>


</body>