ThuVienDienTu/Models/Genres.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ThuVienDienTu.Models
{
    public class Genres
    {
        public int Id { get; set; }
        [Display(Name = "Thể loại")]
        public string GenresName { get; set; }
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
        public virtual ICollection<BookGenres> BookGenres { get; set; }
    }
}

ThuVienDienTu/Models/ViewModels/GenresViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ThuVienDienTu.Models.ViewModels
{
    public class GenresViewModel
    {
        public Genres Genres { get; set; }
        public bool Selected { get; set; }
    }
}

ThuVienDienTu/Areas/Admin/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThuVienDienTu.Data;
using ThuVienDienTu.Models;
using ThuVienDienTu.Utility;

namespace ThuVienDienTu.Areas.Admin.Controllers
{
   // [Authorize(Roles = SD.ADMIN_ROLE + "," + SD.LIBRARIAN_ROLE)]
    [Area("Admin")]
    public class GenresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GenresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Genres
        public async Task<IActionResult> Index()
        {
            return View(await _context.Genres.ToListAsync());
        }

        // GET: Admin/Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genres = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genres == null)
            {
                return NotFound();
            }

            return View(genres);
        }

        // GET: Admin/Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GenresName,Description")] Genres genres)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genres);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genres);
        }

        // GET: Admin/Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genres = await _context.Genres.FindAsync(id);
            if (genres == null)
            {
                return NotFound();
            }
            return View(genres);
        }

        // POST: Admin/Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenresName,Description")] Genres genres)
        {
            if (id != genres.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genres);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenresExists(genres.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genres);
        }

        // GET: Admin/Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genres = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genres == null)
            {
                return NotFound();
            }

            return View(genres);
        }

        // POST: Admin/Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genres = await _context.Genres.FindAsync(id);
            _context.Genres.Remove(genres);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenresExists(int id)
        {
            return _context.Genres.Any(e => e.Id == id);
        }
    }
}

ThuVienDienTu/Areas/Admin/Views/Genres/Create.cshtml
@model ThuVienDienTu.Models.Genres

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Create</h1>

<h4>Genres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenresName" class="control-label"></label>
                <input asp-for="GenresName" class="form-control" />
                <span asp-validation-for="GenresName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ThuVienDienTu/Areas/Admin/Views/Genres/Delete.cshtml
@model ThuVienDienTu.Models.Genres

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genres</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenresName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenresName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ThuVienDienTu/Areas/Admin/Views/Genres/Details.cshtml
@model ThuVienDienTu.Models.Genres

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Genres</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenresName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenresName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ThuVienDienTu/Areas/Admin/Views/Genres/Edit.cshtml
@model ThuVienDienTu.Models.Genres

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<h1>Edit</h1>

<h4>Genres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GenresName" class="control-label"></label>
                <input asp-for="GenresName" class="form-control" />
                <span asp-validation-for="GenresName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ThuVienDienTu/Areas/Admin/Views/Genres/Index.cshtml
@model IEnumerable<ThuVienDienTu.Models.Genres>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/CMS/_CMS.cshtml";
}

<br />
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-info"> Danh sách thể loại</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-area="Admin" asp-controller="Genres" asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Thêm thể loại</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GenresName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GenresName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <div class="btn-group">
                        <a type="button" class="btn btn-success" asp-action="Edit" asp-controller="Genres" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                        <a type="button" class="btn btn-info" asp-action="Details" asp-controller="Genres" asp-route-id="@item.Id"><i class="far fa-list-alt"></i></a>
                        <a type="button" class="btn btn-danger" asp-action="Delete" asp-controller="Genres" asp-route-id="@item.Id"><i class="fas fa-trash-alt"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>